### ISSUE TITLE
Please add LÖVE

### ISSUE THREAD

**Issue by romasch909** [JohnDuncanScott/2d-game-engine-comparison#1]
Hi mate, I'm missing the [LÖVE engine](https://love2d.org/) in your list.

If you don't like Lua, well then it might not be your cup of tea, but if you do like it I suggest you look into it.
Really like it's simple and elegant design which makes it perfect for prototyping (or even for full releases judging by the list of actually released games).

It's cross platform, doesn't need an IDE, open source but the license allows to release commercial games.

And I don't quite understand what you mean by "Coding is in Lua, no easier alternatives", etc. Lua must be one of the easiest languages out there (all power to Lua tables :smile_cat:).

And if you are concerned about performance, LÖVE (and probably other Lua based game engines too) use LuaJIT, which results in performance [comparable to compiled languages](https://www.reddit.com/r/Compilers/comments/llujxv/luajit_performance/), and often faster than Java.

**Comment by JohnDuncanScott** [comment]
Thanks very much for the feedback! I realise that maybe the rejected engines info wasn't very easy to follow. I have put it into table form to make it clearer. I've added Love to that table unfortunately, but hopefully it's clearer why now along with the others :). I added a smaller section near the top about language choice too and included Lua.
